#!/usr/bin/env bash

# Source Credentials --- Note that this is not secure and will leak
# Goal is just to keep them off github
source settings.sh
process="Process Daily Users"

source .env
echo "$BLUESKY_HANDLE"
echo "$BLUESKY_APP_PASSWORD"

log "Script started."

source auth

# Fetch the access JWT
log "Authenticating with Bluesky."
auth "$BLUESKY_HANDLE" "$BLUESKY_APP_PASSWORD"

# Initialize variables for rate limiting
LABEL_LIMIT_REMAINING=3000
LABEL_LIMIT_RESET=0

file="dids_${today}.json"

start=0
end=24

length=$(duckdb "$DATABASE" -json -c "
    SELECT COUNT(*) as count
    FROM unique_dids;
    " | jq -r '.[0].count')

log "$length unique dids observed."

while [ "$start" -le "$length" ]; do
    process_users
done