#!/usr/bin/env bash

# Source Credentials --- Note that this is not secure and will leak
# Goal is just to keep them off github
source .env

source config.sh
source lib/auth
source lib/functions

process="BSKY_SPORTS_BETTING_LABELER"
logfile=sports_betting.log

log "Script started."

# Fetch the access JWT
log "Authenticating with Bluesky."
auth "$BLUESKY_HANDLE" "$BLUESKY_APP_PASSWORD"

# Initialize variables for rate limiting
LABEL_LIMIT_REMAINING=3000
LABEL_LIMIT_RESET=0

log2() {
    jq -nc --arg timestamp "$(date +"%s")" --arg date "$(date +"%Y-%m-%dT%H:%M:%S%z")" --arg did "$did" --arg url "$url" --arg link "$link" --arg cid "$cid" --arg rkey "$rkey" --arg whitelist "$whitelist" '{"timestamp": $timestamp, "date": $date, "level": "INFO", "did": $did, "url": $url, "uri": $link, "cid": $cid, "rkey": $rkey, "whitelist": $whitelist}'
}

# Function to process each post
function process_post() {
    local json="$1"
    local did
    local rkey
    local cid
    local link
    local urls
    local type
    local found

    facet=$(echo "$json" | jq '.record | has("facets")')
    if [ "$facet" = "true" ]; then
        type=$(echo "$json" | jq '[.record.facets[].features[] | select(."$type" == "app.bsky.richtext.facet#link")] | length > 0')
        if [ "$type" = "true" ]; then
            urls=$(echo "$json" | jq -r '
                .record.facets[]
                | .features[]
                | select(."$type" == "app.bsky.richtext.facet#link")
                | .uri')

            # Check if any URIs match the specified domains
            found=0
            for url in $urls; do
                if echo "$url" | grep -iE '(^|.*\.)fanduel\.com|(^|.*\.)draftkings\.com|draftkings\.com|fanduel\.com|betmgm\.com|(^|.*\.)betmgm\.com|sportsbook\.caesars\.com|(^|.*\.)caesars\.com/sportsbook-and-casino|(^|.*\.)espnbet.com|espnbet.com' >/dev/null; then
                    found=1
                    echo "$json" >>flagged_betting_posts.json
                    rkey=$(echo "$json" | jq -r '.rkey')
                    did=$(echo "$json" | jq -r '.did')
                    link=$(echo "$json" | jq -r '"at://" + .did + "/app.bsky.feed.post/" + .rkey')
                    cid=$(get_post_record "$did" "$rkey" | jq -r '.cid')

                    if [ -z "$cid" ]; then
                        log "CID is empty, continuing."
                        continue
                    else

                        whitelist=0
                        if echo "$did" | grep -iE 'a^' >/dev/null; then
                            whitelist=1
                            echo "$(log2)" >>flag_log.json
                            log "Fundraising link $url found at $link with CID $cid and whitelisted DID $did."
                            continue
                        elif echo "$url" | grep -iE 'a^' >/dev/null; then
                            whitelist=1
                            echo "$(log2)" >>flag_log.json
                            log "Whitelisted $url found at $link with CID $cid and $did."
                            continue
                        else
                            log "Fundraising link $url found at $link with CID $cid."
                            echo "$(log2)" >>flag_log.json

                            # Create a label
                            check_rate_limit "$LABEL_LIMIT_REMAINING" "$LABEL_LIMIT_RESET"

                            create_label "$link" "$cid" "sports-betting"
                            log "Label creation response: $response"
                            echo "$response" >>log.json
                            expiredJWT_Check "$response"

                            if [ "$tokenExpired" -eq 1 ]; then
                                create_label "$link" "$cid" "sports-betting"
                                log "Label creation response after token refresh: $response"
                                echo "$response" >>log.json
                            fi
                            if [ "$tokenInvalid" -eq 1 ]; then
                                create_label "$link" "$cid" "sports-betting"
                                log "Label creation response after token refresh: $response"
                                echo "$response" >>log.json
                            fi
                        fi
                    fi
                fi
            done
        fi
    fi

}

# Stream records and process each one
websocat -t -S - autoreconnect:ws://localhost:6008/subscribe?wantedCollections=app.bsky.feed.post | while read -r post; do
    opType=$(echo "$post" | jq -r '.opType')
    if [ "$opType" == "c" ]; then
        process_post "$post"
    fi
done
