#!/usr/bin/env bash

source config.sh
source lib/functions
process="COLLECT_DIDS"
logfile="collect_dids_$(date +"%Y-%m-%d").log"
log "Script started."

function write {
    jq -nc --arg timestamp "$(date +"%Y-%m-%d %H:%M:%S%z")" --arg date "$(date +"%Y-%m-%d")" --arg did "$did" --arg langs "$langs" --arg flagged "$flagged" --arg whitelist "$whitelist" '{"timestamp": $timestamp, "date": $date, "did": $did, "langs": $langs, "flagged": $flagged, "whitelist": $whitelist}'
}

function process {
    local json="$1"
    local opType
    local did
    local langs
    local whitelist
    local flagged

        # Extract the DID and language from the post
        did=$(echo "$json" | jq -r '.did')
        langs=$(echo "$json" | jq -r '.record.langs | join("|")')

        whitelist=0
        flagged=0
        if echo "$langs" | grep -iE 'en|es|fr|de|it|nl|pl|ru|uk' >/dev/null; then
            flagged=1
        fi
        if echo "$langs" | grep -iE 'pt|ja|fa|ps' >/dev/null; then
            whitelist=1
        fi

        if [ "$flagged" -eq 1 ]; then
            log "DID $did flagged for languages: $langs"
            echo "$(write)" >>"dids_$(date +"%Y-%m-%d").json"
        fi
}

# Stream records and process each one
websocat -t - autoreconnect:ws://localhost:6008/subscribe?wantedCollections=app.bsky.feed.post | while read -r post; do
    opType=$(echo "$post" | jq -r '.opType')
    if [ "$opType" == "c" ]; then
        process "$post"
    fi
done