#!/usr/bin/env bash

source settings.sh
process="COLLECT_DIDS"
logfile=collect_dids.log
log "Script started."

function write {
    jq -nc --arg timestamp "$(date +"%Y-%m-%d %H:%M:%S%z")" --arg date "$(date +"%Y-%m-%d")" --arg did "$did" --arg english "$english" --arg whitelist "$whitelist" --arg flagged "$flagged" '{"timestamp": $timestamp, "date": $date, "did": $did, "english": $english, "whitelist": $whitelist, "flagged": $flagged}'
}

function process {
    local json="$1"

    # Extract the DID and language from the post
    did=$(echo "$json" | jq -r '.did')
    langs=$(echo "$json" | jq -r '.commit.record.langs.[]')

    english=0
    whitelist=0
    flagged=0
    for l in $langs; do
        if echo "$l" | grep -iE 'en' >/dev/null; then
            english=1
        elif echo "$l" | grep -iE 'es|fr|de|it|nl|pl|ru|uk' >/dev/null; then
            log "DID $did has language $l."
            flagged=1
        fi
        if echo "$l" | grep -iE 'pt|ja' >/dev/null; then
            whitelist=1
        fi
    done

    if [ "$english" -eq 0 ] && [ "$flagged" -eq 0 ]; then
        log "DID $did not flagged."
    fi

    if [ "$english" -eq 1 ]; then
        log "DID $did is in English."
        echo "$(write)" >> "dids_$(date +"%Y-%m-%d").json"
    elif [ "$flagged" -eq 1 ]; then
        log "DID $did flagged."
        echo "$(write)" >> "dids_$(date +"%Y-%m-%d").json"
    fi
}

# Stream records and process each one
websocat -t - autoreconnect:ws://localhost:6008/subscribe?wantedCollections=app.bsky.feed.post | while read -r post; do
    process "$post"
done
